club_night_app/config/routes.rb
Rails.application.routes.draw do
  get 'club_passwords/new'
  post 'club_passwords/create'
  get 'club_passwords/edit'
  put 'club_passwords/update'
  get 'session/show', to: "session#show"
  get 'session/create_match', to: "session#create_match"
  post 'session/random'
  post 'session/end_game'
  post 'session/need_rest'
  post 'session/end_rest'
  post 'session/fixed_ability'
  get 'session/end_session'
  put 'session/create_match', to: "session#manual_toggle"
  get 'admin_page', to: "memberships#index"
  get 'admin_page/search', to: "memberships#search"



  put 'session/players', to: "session#update_attendance"
  get 'session/players', to: "session#available_members"
  get 'members', to: "members#index"
  get 'find_new_club', to: "search#index"
  devise_for :users, :path => 'u'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :clubs
  resources :users
  resources :memberships

  root "application#home"
  
  get "home", to: "application#home"
  # get "find_new_club", to: "application#find_new_club"
end

club_night_app/app/models/user.rb
class User < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :clubs, through: :memberships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
end

club_night_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!  
    before_action :set_user, only: %i[show edit update destroy]
    
    # def index
    #     @clubs = Club.all
    # end

    def show
        @memberships = Membership.where(user_id:  @user.id)
    end
    
    # def new
    #     @club = Club.new
    # end

    # def create
    #     Club.create(club_params)
    #     redirect_to clubs_path
    # end

    def edit
    end

    def update
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user.destroy
        redirect_to root_path
    end



    private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :about)
    end
end

club_night_app/app/helpers/users_helper.rb
module UsersHelper
end

club_night_app/app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <div class="bg-dark d-flex flex-column text-white justify-content-around align-items-center align-items-middle " style="width: 30vw; border-radius: 20px">

    <div class="m-3">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name %>
    </div>

    <div class="m-3">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email %>
    </div>

    <div class="m-3">
        <%= f.label :About, "About" %>
        <%= f.text_field :about %>
    </div>

<div class="form-group">
    <%= f.submit "Save", class: "btn btn-success m-3" %>
    </div>
    </div>
<% end %>

club_night_app/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form" %>

club_night_app/app/views/users/show.html.erb
<h1> My Profile </h1>
<br>

<div class="row">
  <div class="col-sm-6">
    <div class="card text-white bg-dark mb-3 border border-success" style="max-width: 40vw; border-width: 3px">

      <div class="card-header" style="font-weight: bold">
        <div class="row align-items-center"> 
          <div class="col font-weight-bold" style="font-size: 25px;">
            <%= @user.name  %>
          </div>
        </div>
      </div>

      <div class="card-body">
        <p><span class="bold-label">Email: </span>  <%= @user.email %></p>
        <p><span class="bold-label">About: </span>  <%= @user.about %></p>
        <p><span class="bold-label">Memberships: </span>  <%= @user.memberships.count %></p>
        
        <div class="d-flex justify-content-end">
          <%= link_to("Edit Profile", edit_user_path(@user), class: "btn btn-outline-info btn-sm", style: "margin-right: 5px;") %>
          <%= link_to("Delete My Profile", 
                      user_path(@user),
                      data: {
                              turbo_method: :delete, 
                              turbo_confirm: "Are you sure you want to delete?"
                            }, 
                      class: "btn btn-outline-danger btn-sm") %>
        </div>
      </div>

    </div>
  </div>
</div>

<br>
<br>

<div class="row">
  <div class="col">
    <h2>Clubs you are part of:</h2>
  </div>
  <div class="col-auto">
    <%= link_to("Find new club", find_new_club_path, class: "btn btn-success mt-3") %>
  </div>
</div>
<br>

<div class="row">
  <% @memberships.each do |m| %>
    <div class="col-sm-6">
      <div class="card text-white bg-dark mb-3 border border-success" style="max-width: 40vw; border-width: 3px">

        <div class="card-header" style="font-weight: bold">
          <div class="row align-items-center"> 

            <div class="col font-weight-bold" style="font-size: 20px;">
              <%= m.club.name %>
              <%if m.admin%>
              <span style="color: #198754;"><%= " - Admin" %></span>
              <%end%>
            </div>

            <div class="col-auto", style="margin-bottom: 16px;">
              <%= link_to("View Club", club_path(m.club), class: "btn btn-outline-success mt-3 mx-0") %>
            </div>

          </div>
        </div>

        <div class="card-body">
          <p><span class="bold-label">Founder:</span> <%= m.club.founder %></p>
          <p><span class="bold-label">Location:</span> <%= m.club.location %></p>
          <p><span class="bold-label">Timetable:</span> <%= m.club.timetable %></p>
          <p><span class="bold-label">My Level:</span> <%= m.level %></p>
          <p>
            <span class="bold-label">Members:</span> <%= m.club.users.count %>
            <%= link_to "View Members", members_path(club_id: m.club.id, club_name: m.club.name), class: "btn btn-outline-info btn-sm",  style: "margin-left: 15px;" %>
          </p>

          <div class="d-flex justify-content-end">
            <%= link_to("Edit Membership", edit_membership_path(m, club_id: m.club.id, club_name: m.club.name), class: "btn btn-outline-info btn-sm", style: "margin-right: 5px;") %>
            <%= link_to("Delete Membership", membership_path(m), 
                        data: {
                                turbo_method: :delete, 
                                turbo_confirm: "Are you sure you want to delete?"
                              }, 
                        class: "btn btn-outline-danger btn-sm") %>
          </div>

        </div>

      </div>
    </div>
  <% end %>
</div>


   