club_night_app/config/routes.rb
Rails.application.routes.draw do
  get 'club_passwords/new'
  post 'club_passwords/create'
  get 'club_passwords/edit'
  put 'club_passwords/update'
  get 'session/show', to: "session#show"
  get 'session/create_match', to: "session#create_match"
  post 'session/random'
  post 'session/end_game'
  post 'session/need_rest'
  post 'session/end_rest'
  post 'session/fixed_ability'
  get 'session/end_session'
  put 'session/create_match', to: "session#manual_toggle"
  get 'admin_page', to: "memberships#index"
  get 'admin_page/search', to: "memberships#search"



  put 'session/players', to: "session#update_attendance"
  get 'session/players', to: "session#available_members"
  get 'members', to: "members#index"
  get 'find_new_club', to: "search#index"
  devise_for :users, :path => 'u'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :clubs
  resources :users
  resources :memberships

  root "application#home"
  
  get "home", to: "application#home"
  # get "find_new_club", to: "application#find_new_club"
end

club_night_app/app/models/club.rb
class Club < ApplicationRecord
    has_many :memberships, dependent: :destroy
    has_many :users, through: :memberships

    validates :name, :founder, :location, :timetable, :password, presence: true
    validates :name, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "founder", "id", "location", "name", "timetable", "updated_at"]
end

def self.ransackable_associations(auth_object = nil)
  ["memberships", "users"]
end

end

club_night_app/app/controllers/club_controller.rb
class ClubController < ApplicationController
   before_action :set_club, only: [:show, :edit, :update, :destroy]
    
    def index
        @clubs = Club.all
    end

    def show
    end
    
    def new
        @club = Club.new
    end

    def create
        Club.create(club_params)
        redirect_to clubs_path
    end

    def edit
    end

    def update
        @club.update(club_params)
        redirect_to @club
    end

    def destroy
        @club.destroy
        redirect_to clubs_path
    end



    private
    def set_club
        @club = Club.find(params[:id])
    end

    def club_params
        params.require(:club).permit(:name, :founder, :location, :timetable)
    end
end

club_night_app/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :authenticate_user!  
   before_action :set_club, only: %i[show edit update destroy]
    
    def index
        @clubs = Club.all
        def search
        @query = params[:query]
        @results = Club.where("name LIKE ?", "%#{@query}%")
      end
    end

    def show
        @is_a_member = !Membership.where(user_id: current_user.id, club_id: @club.id).empty?
        @is_admin = !Membership.where(user_id: current_user.id, club_id: @club.id, admin: true).empty?
    end
    
    def new
        @club = Club.new
    end

    def create
        Club.create(club_params)
        redirect_to find_new_club_path
    end

    def edit
    end

    def update
        @club.update(club_params)
        redirect_to @club
    end

    def destroy
        @club.destroy
        redirect_to find_new_club_path
    end

    
    
      



    private
    def set_club
        @club = Club.find(params[:id])
    end

    def club_params
        params.require(:club).permit(:name, :founder, :location, :timetable, :password)
    end
end

club_night_app/app/helpers/clubs_helper.rb
module ClubsHelper
end

club_night_app/app/views/clubs/_form.html.erb
<%= form_for @club do |f| %>

 <div class="bg-dark d-flex flex-column text-white justify-content-around align-items-center align-items-middle " style="width: 30vw; border-radius: 20px">
  <div>
    <div class="m-3">
      <%= f.label :name, style: "display: block" %>
      <%= f.text_field :name %>
    </div>

    <div class="m-3">
      <%= f.label :founder, style: "display: block" %>
      <%= f.text_field :founder %>
    </div>

    <div class="m-3">
      <%= f.label :location, style: "display: block" %>
      <%= f.text_field :location %>
    </div>

    <div class="m-3">
      <%= f.label :timetable, style: "display: block" %>
      <%= f.text_field :timetable%>
    </div>

    <div class="m-3">
      <%= f.label :password, style: "display: block" %>
      <%= f.text_field :password %>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success m-3" %>
    </div>
  </div>
  </div>

<% end %>

club_night_app/app/views/clubs/edit.html.erb
<h1>Edit Club</h1>

<%= render "form" %>

club_night_app/app/views/clubs/index.html.erb
<h1>All Clubs</h1>


<%= link_to "Create New Club", new_club_path %>


<table>
    <tr>
        <th>Name</th>
        <th>Founder</th>
        <th>Location</th>
        <th>Timetable</th>
    </tr>

    <% @clubs.each do |club| %>
        <tr>
        <td><%= link_to(club.name, club_path(club)) %></td>
        <td><%= club.founder%></td>
        <td><%= club.location %></td>
        <td><%= club.timetable %></td>
        <td>
            <%= link_to "Edit Club", edit_club_path(club) %>
            &nbsp;|&nbsp;
            <%= link_to "Delete Club", club_path(club),
                data: {
                    turbo_method: :delete, 
                    turbo_confirm: "Are you sure you want to delete #{club.name}?"} %>
        </td>
            
        

        </tr>
    <% end %>
</table>

club_night_app/app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render "form" %>

<br>
<br>

<div>
  <%= link_to("Back to All Clubs", find_new_club_path, class: "btn btn-info") %>
</div>

club_night_app/app/views/clubs/show.html.erb
<div class="container">


<div class="d-flex justify-content-between align-items-center">
  <% if @is_a_member%>
  <div>
  <h1><%= @club.name %></h1>
  <p><span style="font-style: italic; font-size: 120%;">you are a member 
    <% if @is_admin%>
       and an admin</span></p>
    <%else%>
    </span></p>
    <%end%>
</div>

  <%else%>
    <h1><%= @club.name %> <br><%= link_to("Join #{@club.name}", new_membership_path(club_id: @club.id, club_name: @club.name), class: "btn btn-success") %></h1>
  <%end%>

  <% if @is_admin%>
  <div class="d-flex justify-content-end">
    <%= link_to("Edit Club", edit_club_path(@club), class: "btn btn-outline-info btn-sm m-2") %>
    <%= link_to("Delete Club", club_path(@club), data: {
                                turbo_method: :delete, 
                                turbo_confirm: "Are you sure you want to delete?"
                              }, 
                        class: "btn btn-outline-danger btn-sm m-2") %>

  </div>
  <%end%>

</div>
  

  <div class="row mt-4">
    <div class="col-md-6">
      <div class="card text-white bg-dark text-center">
      <div class="card-header"><h5>Founder</h5></div>
        <div class="card-body ">
          <p class="card-text"><%= @club.founder %></p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card text-white bg-dark text-center">
        <div class="card-header"><h5 class="card-title">Location</h5></div>
        <div class="card-body text-center">
          <p class="card-text"><%= @club.location %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">
      <div class="card text-white bg-dark text-center">
        <div class="card-header"><h5 class="card-title">Timetable</h5></div>
        <div class="card-body text-center">
          <p class="card-text" style="margin-bottom: 10px;"><%= @club.timetable %></p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card text-white bg-dark text-center">
        <div class="card-header"><h5 class="card-title">Members</h5></div>

        <div class="card-body text-center">

            <span class="bold-label"><%=pluralize(@club.users.count, "Member")%></span> 
            <%= link_to "View Members", members_path(club_id: @club.id, club_name: @club.name), class: "btn btn-outline-info btn-sm",  style: "margin-left: 15px;" %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="d-flex justify-content-between align-items-center">
  <%= link_to("Back to All Clubs", find_new_club_path, class: "btn btn-info mt-3") %>

  <% if @is_admin%>
    <%= link_to("Start Session", session_show_path(club: @club), class: "btn btn-warning mt-3") %>
  <%end%>
</div>