club_night_app/config/routes.rb
Rails.application.routes.draw do
  get 'club_passwords/new'
  post 'club_passwords/create'
  get 'club_passwords/edit'
  put 'club_passwords/update'
  get 'session/show', to: "session#show"
  get 'session/create_match', to: "session#create_match"
  post 'session/random'
  post 'session/end_game'
  post 'session/need_rest'
  post 'session/end_rest'
  post 'session/fixed_ability'
  get 'session/end_session'
  put 'session/create_match', to: "session#manual_toggle"
  get 'admin_page', to: "memberships#index"
  get 'admin_page/search', to: "memberships#search"



  put 'session/players', to: "session#update_attendance"
  get 'session/players', to: "session#available_members"
  get 'members', to: "members#index"
  get 'find_new_club', to: "search#index"
  devise_for :users, :path => 'u'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :clubs
  resources :users
  resources :memberships

  root "application#home"
  
  get "home", to: "application#home"
  # get "find_new_club", to: "application#find_new_club"
end

club_night_app/app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :authenticate_user!  

  def show
    @club = Club.find(params[:club])
    @members = params[:members]
  end

  def available_members
    @club = Club.find(params[:club])
  end

  def update_attendance
    @membership = Membership.find(params[:membership])
    puts "PASSWORD: #{@membership.password}"
    @membership.present = params[:present] || false
    @membership.club_password = "password"
    @membership.save
  end

  def random
    puts "RANDOM METHOD"
    @existing_players = Membership.where(club_id: params[:club_id], court: params[:court])
    @random_players = Membership.where(waiting_to_play: true, club_id: params[:club_id], present: true).order(Arel.sql('RANDOM()')).limit(4) 
  
    @random_players.each do |player| 
      puts " PLAYERRRRRRRR #{player.user.name}"
      player.waiting_to_play = false
      player.court = params[:court]
      player.club_password = "password"
      player.save
    end
    redirect_to session_show_path(club: params[:club_id])
  end

  def fixed_ability
    @random_players = Membership.where(waiting_to_play: true, club_id: params[:club_id], present: true, level: params[:level]).order(Arel.sql('RANDOM()')).limit(4) 
    @random_players.each do |player| 
      player.waiting_to_play = false
      player.court = params[:court]
      player.club_password = "password"
      player.save
    end
    redirect_to session_show_path(club: params[:club_id])
  end

  def end_game
    @players = Membership.where(club_id: params[:club_id], present: true, court: params[:court])
    @players.each do |player|
      player.waiting_to_play = true
      player.court = 0
      player.club_password = "password"
      player.save
    end
    redirect_to session_show_path(club: params[:club_id])
  end

  def need_rest
    @membership = Membership.find(params[:membership])
    @membership.resting = true
    @membership.waiting_to_play = false
    @membership.club_password = "password"
    @membership.save
    redirect_to session_show_path(club: params[:club_id])
  end

  def end_rest
    @membership = Membership.find(params[:membership])
    @membership.resting = false
    @membership.waiting_to_play = true
    @membership.club_password = "password"
    @membership.save
    redirect_to session_show_path(club: params[:club_id])
  end

  def create_match
    puts "INNNN HEREEE"
    @existing_players = Membership.where(club_id: params[:club_id], present: true, court: params[:court], waiting_to_play: false)
    @existing_players.each do |player| 
      player.waiting_to_play = true
      player.court = 0
      player.club_password = "password"
      player.save
    end
  end

  def end_session
  @players_playing = Membership.where(club_id: params[:club_id]).where("court > ?", 0)
  @players_playing.each do |player| 
    player.waiting_to_play = true
    player.court = 0
    player.club_password = "password"
    player.save
  end
  redirect_to club_path(params[:club_id])

  end

  def manual_toggle
    @membership = Membership.find(params[:membership][:id])
    @membership.court = params[:membership][:court]
    @membership.waiting_to_play = false
    @membership.club_password = "password"
    @membership.save
    # @players_selected = Membership.where(club_id: @membership.club_id, court: params[:membership][:court]).count
    # puts "============++++++++++ #{@players_selected}"
  end



  # def confirm_players
  #   @players = Membership.where(club_id: params[:club_id], present: true, court: params[:court])
    
  # end

end

club_night_app/app/helpers/session_helper.rb
module SessionHelper
end

club_night_app/app/views/session/_manual_form.html.erb
<%= form_with(model: membership, method: :put) do |form| %>

<% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this player from being selected</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <%= form.hidden_field :id, value: membership.id %>
  
  <div class="container p-2">
    <div class="align-items-center">
        <%= form.check_box :court,
        { class: "form-check-input", onchange: "this.form.submit()", checked: membership.court == court },
        court, 0 %>
  </div>
</div>

</div>
<% end %>

club_night_app/app/views/session/_membership_form.html.erb
<%= form_with(method: :put) do |form| %>

<div class="form-check form-switch container">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= form.hidden_field :membership, value: membership.id %>

 <div class="container p-2" style="width: 30vw;">
  <div class="align-items-center">
    <%= form.check_box :present,
      { class: "form-check-input toggle-switch", onchange: "this.form.submit()", checked: membership.present? },
      true, false %>
    <span class="ml-2"><%= membership.user.name %></span>
  </div>
</div>

</div>

<% end %>

club_night_app/app/views/session/_ready_form.html.erb
<div class = "ready-form-container">
<form action="<%= session_end_rest_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :membership, membership %>
  <%= hidden_field_tag :club_id, club_id %>

  <button type="submit" class="btn btn-outline-success">Ready to play ✅</button>
</form>
</div>

club_night_app/app/views/session/_resting_form.html.erb
<div class = "resting-form-container">
<form action="<%= session_need_rest_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :membership, membership %>
  <%= hidden_field_tag :club_id, club_id %>

  <button type="submit" class="btn btn-outline-warning">Needs a rest 💤</button>
</form>
</div>

club_night_app/app/views/session/available_members.html.erb
<h3>Toggle players who are present</h3>



<%@club.users.each_slice(3) do |memberships|%>
    <div class="row">
        <% memberships.each do |u| %>
            <div class="list-group-item col-md-4 align-items-center align-items-middle" style="margin-bottom: 5px">
                <%membership = Membership.find_by(user_id: u.id, club_id: @club.id)%>
                <%=form_tag do%>
                    <%= render 'membership_form', u: u, membership: membership%>
                <%end%>
            </div>
        <%end%>
    </div>
<%end%>


<%= link_to("Back to Session", session_show_path(club: @club), class: "btn btn-success mt-3") %>
<%# update_membership_path(membership.id) %>

<%# Manually add the url/path to the form to submit the POST request  %>
<%# Make sure I define a PUT/PATCH route to call on form submit %>

club_night_app/app/views/session/create_match.html.erb
<h1>Create Match for <%= "#{Club.find(params[:club_id]).name} - Court #{params[:court]}"%> </h1>

<br>
<br>



<div class="button-container d-flex justify-content-around">
    <%= form_tag(
        { controller: "session", action: "random", club_id: params[:club_id], court: params[:court] },
         method: :post) do %>
        <%= submit_tag "Random", class: "btn btn-info btn-lg random-players" %>
      <% end %>

<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">
  Fixed Abilty
</button>

  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal2">
  Manual
</button>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Ability Selector</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="background-color: red; color: white;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-around">

        <%= form_tag(
        { controller: "session", action: "fixed_ability", club_id: params[:club_id], court: params[:court], level: "Beginner" },
         method: :post) do %>
        <%= submit_tag "Beginner (#{Membership.where(waiting_to_play: true, club_id: params[:club_id], present: true, level: "Beginner").count} available)", class: "btn btn-primary random-players" %>
      <% end %>

        <%= form_tag(
        { controller: "session", action: "fixed_ability", club_id: params[:club_id], court: params[:court], level: "Intermediate" },
         method: :post) do %>
        <%= submit_tag "Intermediate (#{Membership.where(waiting_to_play: true, club_id: params[:club_id], present: true, level: "Intermediate").count} available)", class: "btn btn-primary" %>
      <% end %>

        <%= form_tag(
        { controller: "session", action: "fixed_ability", club_id: params[:club_id], court: params[:court], level: "Expert" },
         method: :post) do %>
        <%= submit_tag "Expert (#{Membership.where(waiting_to_play: true, club_id: params[:club_id], present: true, level: "Expert").count} available)", class: "btn btn-primary " %>
      <% end %>

      </div>
    </div>
  </div>
</div>




<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header d-flex justify-content-between align-items-center">
        <h5 class="modal-title" id="myModalLabel">Manual Selection - <%= link_to("Create", session_show_path(club: params[:club_id]), class: "btn btn-outline-success mb-1") %></h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="background-color: red; color: white;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="d-table m-3">
        <table class = "table table-dark table-striped">
          <thead>
            <tr>
              <th class="col-2" style="color: #1d8454;">Beginner</th>
              <th class="col-1" style="color: #1d8454;">Select</th>
            </tr>
          </thead>

          <tbody>
            <% Membership.where(club_id: params[:club_id], present: true, waiting_to_play: true, level: "Beginner").each do |membership| %>
              <tr>
                <td class="col-2 align-middle"> <%= membership.user.name%>  </td>
                <td class="col-1">
                  <%=form_tag do%>
                    <%= render 'manual_form', court: params[:court], membership: membership %>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="d-table m-3">
        <table class = "table table-dark table-striped">
          <thead>
            <tr>
              <th class="col-2" style="color: #1d8454;">Intermediate</th>
              <th class="col-1" style="color: #1d8454;">Select</th>
            </tr>
          </thead>

          <tbody>
            <% Membership.where(club_id: params[:club_id], present: true, waiting_to_play: true, level: "Intermediate").each do |membership| %>
              <tr>
                <td class="col-2 align-middle"> <%= membership.user.name%>  </td>
                <td class="col-1">
                  <%=form_tag do%>
                    <%= render 'manual_form', court: params[:court], membership: membership %>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="d-table m-3">
        <table class = "table table-dark table-striped">
          <thead>
            <tr>
              <th class="col-2 align-middle" style="color: #1d8454;">Expert</th>
              <th class="col-1" style="color: #1d8454;">Select</th>
            </tr>
          </thead>

          <tbody>
            <% Membership.where(club_id: params[:club_id], present: true, waiting_to_play: true, level: "Expert").each do |membership| %>
              <tr>
                <td class="col-2"> <%= membership.user.name%>  </td>
                <td class="col-1">
                  <%=form_tag do%>
                    <%= render 'manual_form', court: params[:court], membership: membership %>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="modal-footer">
        <%= link_to("Create", session_show_path(club: params[:club_id]), class: "btn btn-outline-success mb-1") %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal" style="background-color: red; color: white;">Close</button>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>


<div class="row">
  <div class="container players-waiting">
    <h3>Available Players</h3>
    <ul class="list-group">
      <% Membership.where(waiting_to_play: true, club_id: params[:club_id], present: true).each_slice(3) do |memberships| %>
        <li class="row">
          <% memberships.each do |membership| %>
            <div class="list-group-item col-md-4 text-white bg-dark" style="margin-bottom: 5px">
              <div class="d-flex align-items-center align-items-middle justify-content-between">
              <p style= "margin: 0">
              <%= membership.user.name %>
              <span style="font-style: italic; color: gray; font-size: 15px;"> <%= " - #{membership.level}" %></span>
              </p>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

club_night_app/app/views/session/show.html.erb
<%= javascript_include_tag 'session' %>

<div class="d-flex justify-content-between align-items-center">
  <h1><%=@club.name %> - Session Started</h1>
  <%= link_to("End Session", session_end_session_path(club_id: @club), class: "btn btn-danger mt-3") %>
</div>

<%= link_to("Toggle Players Present", session_players_path(club: @club), class: "btn btn-success mt-3 btn-thick-border") %>

<br>
<br>


<div class="container">

  <div class="row">

    <div class="col-md-3 text-center">

      <h3>Court 1</h3>

      <div class="court court1">


          <% Membership.where(
            court: 1, club_id: @club.id, present: true)
            .order(updated_at: :asc)
            .each do |membership| %>

            <div class="d-flex align-items-center justify-content-center flex-column">
              <p style="margin: 0;"><%= membership.user.name %></p>
              <p style="font-style: italic; font-size: 12px;"><%= "(#{membership.level})" %></p>
            </div>

          <% end %>


      </div>

      <%= link_to("Create Match", session_create_match_path(court: 1, club_id: @club), class: "btn btn-outline-success mt-3") %>

      <br>
      <br>

      <%= form_tag(
        { controller: "session", action: "end_game", club_id: @club.id, court: 1},
         method: :post) do %>
          <%= submit_tag "End Match", class: "btn btn-outline-danger end1" %>
        <% end %>

    </div>

    <div class="col-md-3 text-center">

      <h3>Court 2</h3>

      <div class="court court2">

          <% Membership.where(
            court: 2, club_id: @club.id, present: true)
            .order(updated_at: :asc)
            .each do |membership| %>

            <div class="d-flex align-items-center justify-content-center flex-column">
              <p style="margin: 0;"><%= membership.user.name %></p>
              <p style="font-style: italic; font-size: 12px;"><%= "(#{membership.level})" %></p>
            </div>

          <% end %>

      </div>

      <%= link_to("Create Match", session_create_match_path(court: 2, club_id: @club), class: "btn btn-outline-success mt-3") %>

      <br>
      <br>

      <%= form_tag(
        { controller: "session", action: "end_game", club_id: @club.id, court: 2},
         method: :post) do %>
          <%= submit_tag "End Match", class: "btn btn-outline-danger" %>
        <% end %>

    </div>

    <div class="col-md-3 text-center">

      <h3>Court 3</h3>

      <div class="court court2">



          <% Membership.where(
            court: 3, club_id: @club.id, present: true)
            .order(updated_at: :asc)
            .each do |membership| %>

            <div class="d-flex align-items-center justify-content-center flex-column">
              <p style="margin: 0;"><%= membership.user.name %></p>
              <p style="font-style: italic; font-size: 12px;"><%= "(#{membership.level})" %></p>
            </div>

          <% end %>



      </div>

      <%= link_to("Create Match", session_create_match_path(court: 3, club_id: @club), class: "btn btn-outline-success mt-3") %>
      
      <br>
      <br>
      
      <%= form_tag(
        { controller: "session", action: "end_game", club_id: @club.id, court: 3},
         method: :post) do %>
          <%= submit_tag "End Match", class: "btn btn-outline-danger" %>
        <% end %>

    </div>

    <div class="col-md-3 text-center">

      <h3>Court 4</h3>

      <div class="court">


          <% Membership.where(
            court: 4, club_id: @club.id, present: true)
            .order(updated_at: :asc)
            .each do |membership| %>

            <div class="d-flex align-items-center justify-content-center flex-column">
              <p style="margin: 0;"><%= membership.user.name %></p>
              <p style="font-style: italic; font-size: 12px;"><%= "(#{membership.level})" %></p>
            </div>

          <% end %>


      </div>

      <%= link_to("Create Match", session_create_match_path(court: 4, club_id: @club), class: "btn btn-outline-success mt-3") %>
      
      <br>
      <br>

      <%= form_tag(
        { controller: "session", action: "end_game", club_id: @club.id, court: 4},
         method: :post) do %>
          <%= submit_tag "End Match", class: "btn btn-outline-danger" %>
        <% end %>

    </div>

  </div>

</div>

<br>
<br>




<div class="row">
  <div class="col-md-6">
    <div class="container players-waiting" style="border: 1px solid black; background-color: #f3ebe3;">
      <h3 class="mt-2">Players Waiting</h3>
      <ul class="list-group">
        <% Membership.where(waiting_to_play: true, club_id: @club.id, present: true).each do |membership| %>
          <li class="list-group-item text-white bg-dark" style="margin-bottom: 5px">
            <div class="d-flex align-items-center align-items-middle justify-content-between ">
              <p style= "margin: 0">
              <%= membership.user.name %>
              <span style="font-style: italic; color: gray; font-size: 15px;"> <%= " - #{membership.level}" %></span>
              </p>
              <%= render "resting_form", membership: membership.id, club_id: @club.id %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-6">
    <div class="container players-resting" style="border: 1px solid black; background-color: #f3ebe3;">
      <h3 class="mt-2">Players Resting</h3>
      <ul class="list-group">
        <% Membership.where(resting: true, club_id: @club.id, present: true).each do |membership| %>
          <li class="list-group-item text-white bg-dark" style="margin-bottom: 5px">
             <div class="d-flex align-items-center align-items-middle justify-content-between">
              <p style= "margin: 0">
              <%= membership.user.name %>
              <span style="font-style: italic; color: gray; font-size: 15px;"> <%= " - #{membership.level}" %></span>
              </p>
              <%= render "ready_form", membership: membership.id, club_id: @club.id %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>



<script>
console.log('Script executed successfully');

  window.addEventListener('beforeunload', function() {
    console.log("IN SETTER")
    localStorage.setItem('scrollPosition', window.pageYOffset);
  });

  document.addEventListener('DOMContentLoaded', function() {
  if (window.location.hash) {
    const scrollPosition = parseInt(window.location.hash.split('-')[1]);
    window.scrollTo(0, scrollPosition);
  }
});
</script>